name: Service CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    uses: YOUR_ORG/skillcareer-infra/.github/workflows/reusable-ci.yml@main
    with:
      node_version: "18"
      image_name: "user-service"
    secrets: inherit
